### ISSUE TITLE
Unable to Update Layer Classification

### ISSUE THREAD

**Issue by TheMapSmith** [Esri/weighted-raster-overlay-service-toolbox#39]
Hello! 

Thank you so much for your help fixing #37! I'm continuing with my publishing workflow, and I'm now running into an issue where I can't properly set the ranges for certain layers. 

**Process:**
1. Create the WRO Mosaic 
2. Run the WRO Layer Classification to configure a layer 
3. Re-run the WRO Layer Classification tool to double-check the values were set 

**Result:** 
1. No layer configurations are shown in the Geoprocessing tool UI 
2. The previously configured layer is not shown properly in the Suitability Modeler when published 
3. However, a green check is shown in the GP history ✅ 

Upon loading a Mosaic Layer into the GeoProcessing tool, I see this error: 

_Error screenshot_
![image](https://github.com/Esri/weighted-raster-overlay-service-toolbox/assets/8357118/05532874-4086-48b9-bb1f-8c8c68b07cfa)

Based on the screenshot, this is where the error is happening 

https://github.com/Esri/weighted-raster-overlay-service-toolbox/blob/c125bd936a6fcea6412662aec2fc8a83255fe0d1/WROS/Weighted%20Raster%20Overlay%20Service.pyt#L159-L164

What's interesting to me here is that the Layer Data section is blank, even though I had just run the tool in a previous step 

_Just prior to receiving that error, I successfully ran the tool to configure the layer data. Screenshot:_
![ArcGISPro_qLu2yxo7Fv](https://github.com/Esri/weighted-raster-overlay-service-toolbox/assets/8357118/fa002a7d-98b9-4f41-bcab-1e142c196ec9)

Here is the Python snippet from this previous run 

```python
arcpy.wroservice.UpdateWROClassification(
    inMosaic=r"C:\Users\Steve\Documents\ArcGIS\Projects\All\AllLayer_WRO.gdb\All",
    in_mosaic_row="L_V",
    wroTitle="Uso y Cobertura de la Tierra: Vegetation",
    mosaicLayerData="'Desert, barren and rocky areas' 6 7 1;Forest 7 9 1;'Fragmented forest' 9 10 1;Grassland 10 18 1;'Secondary forest' 18 19 1;Shrubland 19 21 1"
)
```

I'd like to be able to show class names (like Desert, Forest, etc) to the end-user rather than integer range values (3-4, 4-5, etc) so the user understands the values being mapped. 

![image](https://github.com/Esri/weighted-raster-overlay-service-toolbox/assets/8357118/342699de-c8a3-446b-94c8-d7e1948b44ca)

Can you help me understand why I'm not able to configure these layers? 

Thanks!

**Comment by kennethWalton** [comment]
Hey again @TheMapSmith ! I'll have a developer look at this issue as well.

**Comment by nmpeterson** [comment]
Hi @TheMapSmith. It looks like this error is popping up because of the comma in your range label "Desert, barren and rocky areas". We are going to determine how best to handle this in future cases, but the immediate fix for you would be to remove that comma from your range label.

Since you won't be able to do so by running the tool, you can open your mosaic dataset's attribute table in ArcGIS Pro, find the "RangeLabels" attribute for the L_V layer, and modify the value to remove that comma.

**Comment by kennethWalton** [comment]
@TheMapSmith We have merged a change into the master branch which will replace commas in the range label, which should help prevent issues caused by the use of commas. I'll log another Github issue to enhance the tools to allow the use of commas in the range labels. We are currently investigating the best way to do this, as it would affect consuming weighted overlay services in other apps as well.

**Comment by kennethWalton** [comment]
Logged the following issue for the enhancement: #41
